##SPRING CONF
#
#server:
#  port: 8080
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: trace
#            BasicBinder: TRACE
#
#spring:
#  profiles: dev
#
#  jpa:
#    defer-datasource-initialization: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#      generate-ddl: true
#
#  integration:
#    management:
#      default-logging-enabled: true
#
#  liquibase:
#    enabled: false
#
##  ACTUATOR
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custo
