#SPRING CONF

server:
  port: 8080

spring:

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true

  integration:
    management:
      default-logging-enabled: true

  liquibase:
    enabled: false

  banner:
    location: "classpath:/banner/bannerDev.txt"

#  ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"

#LOGGING
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
            BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui-custo
